variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # We want full history so that "git describe" always works correctly.
  GIT_DEPTH: 0
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"

test:
  stage: test

  image: golang:$IMAGE_TAG

  before_script:
    - apk --update add make gcc musl-dev git-lfs
    - git lfs fetch
    - (cd /go; go install gotest.tools/gotestsum@v1.8.0)
    - (cd /go; go install github.com/boumenot/gocover-cobertura@v1.2.0)

  script:
    - make test-ci

  artifacts:
    when: always
    reports:
      junit: tests.xml
      cobertura: coverage.xml
    paths:
      - coverage.html
    expire_in: never

  # This has to be set in project's settings (CI/CD -> General pipelines section) as well.
  coverage: '/coverage: \d+\.\d+% of statements/'

  parallel:
    matrix:
      - IMAGE_TAG: ['1.18-alpine3.14']

lint:
  stage: test

  image: golang:1.18-alpine3.14

  before_script:
    - apk --update add make gcc musl-dev
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2

  script:
    - make lint-ci

  artifacts:
    when: always
    reports:
      codequality: codeclimate.json
    expire_in: never

fmt:
  stage: test

  image: golang:1.18-alpine3.14

  before_script:
    - apk --update add make git gcc musl-dev grep git-lfs
    - git lfs fetch
    - go install mvdan.cc/gofumpt@v0.3.1
    - go install golang.org/x/tools/cmd/goimports@v0.1.10

  script:
    - make fmt-ci

lint_docs:
  stage: test

  image: node:17-alpine3.14

  before_script:
    - apk --update add make

  script:
    - make lint-docs

audit:
  stage: test

  image: golang:1.18-alpine3.14

  before_script:
    - apk --update add make git gcc musl-dev git-lfs
    - git lfs fetch
    - go install github.com/sonatype-nexus-community/nancy@v1.0.33

  script:
    - make audit

commits:
  stage: test

  image: golang:1.18-alpine3.14

  variables:
    GIT_DEPTH: "0"

  before_script:
    - apk --update add git

  script:
    - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'

publish:
  stage: deploy

  image: golang:1.18-alpine3.14

  script:
    - GOPROXY=proxy.golang.org go list -m "gitlab.com/tozd/go/mediawiki@$CI_COMMIT_REF_NAME"

  rules:
    # Only on protected tags on main repository. Protected tags start with "v".
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /^v/ && $CI_PROJECT_PATH == "tozd/go/mediawiki"'

  # We do not need build artifacts in this job.
  dependencies: []

sync_releases:
  stage: deploy

  image:
    name: registry.gitlab.com/tozd/gitlab/release/tag/v0-2-1:latest-debug
    entrypoint: [""]

  script:
    - /gitlab-release

  rules:
    # Protected tags start with "v".
    - if: '$GITLAB_API_TOKEN && ($CI_COMMIT_BRANCH == "main" || ($CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /^v/))'

  # We do not need build artifacts in this job.
  dependencies: []

sync_config:
  stage: deploy

  image:
    name: registry.gitlab.com/tozd/gitlab/config/tag/v0-3-0:latest-debug
    entrypoint: [""]

  script:
    - /gitlab-config set

  rules:
    - if: '$GITLAB_API_TOKEN && $SOPS_AGE_KEY_FILE && $CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-conf.yml

  # We do not need build artifacts in this job.
  dependencies: []
